const { Restaurant } = require('../services/db/models/restaurant.model');

const createRestaurants = async () => {
  try {

    await Restaurant.bulkCreate([
      {
        user_id: 1,
        name: 'La not Vaquita loca',
        description: 'Very tasty vegan not milk drinks',
        speciality: 'Bebidas veganas',
        phone_number: 123123123,
        address: 'Calle (not)lactea 123',
        city: 'Chimbarongo',
        time_open: '08:00',
        time_close: '21:00',
      },
      {
        name: 'Vegano Express',
        speciality: 'Comida rápida vegana',
        city: 'Santiago',
        phone_number: 555555555,
        address: 'Av. de las Verduras, 567',
        description: 'Sabores rápidos y saludables',
        time_open: '10:00',
        time_close: '21:00',
        user_id: 2,
        role_id: 2,
      },
      {
        name: 'La Parrilla de la Huerta',
        speciality: 'Asados de vegetales',
        city: 'Ñuñoa',
        phone_number: 666666666,
        address: 'Calle de las Barbacoas, 789',
        description: 'Sabores a la parrilla, pero veganos',
        time_open: '12:00',
        time_close: '23:00',
        user_id: 3,
        role_id: 2,
      },
      {
        name: 'Mar de Algas',
        speciality: 'Cocina marina vegana',
        city: 'Viña del Mar',
        phone_number: 777777777,
        address: 'Paseo de las Olas, 101',
        description: 'Sabores del océano sin sacrificios',
        time_open: '11:30',
        time_close: '22:30',
        user_id: 4,
        role_id: 2,
      },
      {
        name: 'El Jardín de los Sabores',
        speciality: 'Platos de temporada',
        city: 'Providencia',
        phone_number: 888888888,
        address: 'Calle de las Flores, 432',
        description: 'Cocina basada en ingredientes frescos',
        time_open: '09:30',
        time_close: '20:30',
        user_id: 5,
        role_id: 2,
      },
      {
        name: 'Sabor del Este',
        speciality: 'Cocina asiática vegana',
        city: 'Santiago',
        phone_number: 999999999,
        address: 'Av. del Bambú, 210',
        description: 'Viaje culinario por el continente asiático',
        time_open: '12:00',
        time_close: '22:00',
        user_id: 6,
        role_id: 2,
      },
      {
        name: 'Mediterráneo Verde',
        speciality: 'Sabores del Mediterráneo',
        city: 'Viña del Mar',
        phone_number: 1010101010,
        address: 'Paseo de las Olivas, 303',
        description: 'Inspírate en la dieta mediterránea',
        time_open: '11:00',
        time_close: '21:00',
        user_id: 7,
        role_id: 2,
      },
      {
        name: 'Raíces Andinas',
        speciality: 'Platos de la región andina',
        city: 'Ñuñoa',
        phone_number: 1111111111,
        address: 'Calle de los Andes, 789',
        description: 'Sabores auténticos de la cordillera',
        time_open: '10:30',
        time_close: '20:30',
        user_id: 8,
        role_id: 2,
      },
      {
        name: 'El Rincón Vegano',
        speciality: 'Comida casera vegana',
        city: 'Santiago',
        phone_number: 1212121212,
        address: 'Calle de la Tranquilidad, 123',
        description: 'Platos caseros con amor y sabor vegano',
        time_open: '09:00',
        time_close: '20:00',
        user_id: 9,
        role_id: 2,
      },
      {
        name: 'Cosecha Fresca',
        speciality: 'Ensaladas y smoothies',
        city: 'Providencia',
        phone_number: 1313131313,
        address: 'Av. de las Frutas, 456',
        description: 'Ingredientes frescos para tu bienestar',
        time_open: '08:30',
        time_close: '19:30',
        user_id: 10,
        role_id: 2,
      },
      {
        name: 'Sabor Auténtico',
        speciality: 'Comida latinoamericana vegana',
        city: 'Ñuñoa',
        phone_number: 1414141414,
        address: 'Calle de las Especias, 789',
        description: 'Sabores tradicionales sin carne',
        time_open: '11:30',
        time_close: '22:30',
        user_id: 10,
        role_id: 2,
      },
    ]);

    console.log('Restaurant creados');
  } catch (err) {
    console.log('Error al cargar Restaurant', err);
  }
};

module.exports = { createRestaurants };
